name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: rumanak/lab2_javagradle  # Docker image name

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Display message
        run: echo "Hi, I am from COSC 1209 class"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permissions for Gradle (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build --no-daemon --info

      # Fix: Corrected Windows conditional execution
      - name: Run platform-specific command
        shell: bash  # Ensures correct shell is used for Linux/macOS
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "Running on Windows"
          else
            echo "Running on Linux/macOS"
          fi

      # Docker login step (only for Ubuntu)
      - name: Log in to Docker Hub
        if: runner.os == 'Linux'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker Image (only for Ubuntu)
      - name: Build Docker Image
        if: runner.os == 'Linux'
        run: docker build -t ${{ env.IMAGE_NAME }} .

      # Push Docker Image to Docker Hub (only for Ubuntu)
      - name: Push Docker Image to Docker Hub
        if: runner.os == 'Linux'
        run: docker push ${{ env.IMAGE_NAME }}:latest

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
